version: "3"

services:
  nginx-reverse-proxy-okta:
    image: thecloudgarage/nginx-reverse-proxy-okta:with-env
    container_name: nginx-reverse-proxy-okta
    ports:
      - "80:80"
    environment:
      - okta_url=dev-xxxxx.okta.com
      - okta_client_id=yyyyyyyyyyyyyyyy
      - okta_client_secret=zzzzzzzzzzzzzzzz
